package br.com.fnis.xmlns.services.consultaacoesatendimentoservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-06T16:57:40.225-03:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "ConsultaAcoesAtendimentoService_V1", 
                  wsdlLocation = "file:/D:/Projetos/Openshift/spring-boot-cxf-ws/fis_camel_cxfws_app/wsdl/ConsultaAcoesAtendimentoService_V1_1.wsdl",
                  targetNamespace = "http://xmlns.fnis.com.br/Services/ConsultaAcoesAtendimentoService/V1") 
public class ConsultaAcoesAtendimentoServiceV1_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.fnis.com.br/Services/ConsultaAcoesAtendimentoService/V1", "ConsultaAcoesAtendimentoService_V1");
    public final static QName ConsultaAcoesAtendimentoServiceV1SOAP = new QName("http://xmlns.fnis.com.br/Services/ConsultaAcoesAtendimentoService/V1", "ConsultaAcoesAtendimentoService_V1SOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Projetos/Openshift/spring-boot-cxf-ws/fis_camel_cxfws_app/wsdl/ConsultaAcoesAtendimentoService_V1_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaAcoesAtendimentoServiceV1_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Projetos/Openshift/spring-boot-cxf-ws/fis_camel_cxfws_app/wsdl/ConsultaAcoesAtendimentoService_V1_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaAcoesAtendimentoServiceV1_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaAcoesAtendimentoServiceV1_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaAcoesAtendimentoServiceV1_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ConsultaAcoesAtendimentoServiceV1_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConsultaAcoesAtendimentoServiceV1_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConsultaAcoesAtendimentoServiceV1_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ConsultaAcoesAtendimentoServiceV1
     */
    @WebEndpoint(name = "ConsultaAcoesAtendimentoService_V1SOAP")
    public ConsultaAcoesAtendimentoServiceV1 getConsultaAcoesAtendimentoServiceV1SOAP() {
        return super.getPort(ConsultaAcoesAtendimentoServiceV1SOAP, ConsultaAcoesAtendimentoServiceV1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaAcoesAtendimentoServiceV1
     */
    @WebEndpoint(name = "ConsultaAcoesAtendimentoService_V1SOAP")
    public ConsultaAcoesAtendimentoServiceV1 getConsultaAcoesAtendimentoServiceV1SOAP(WebServiceFeature... features) {
        return super.getPort(ConsultaAcoesAtendimentoServiceV1SOAP, ConsultaAcoesAtendimentoServiceV1.class, features);
    }

}
