
package br.com.fnis.xmlns.services.consultaacoesatendimentoservice.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-06T16:57:40.177-03:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "FISFaultService", targetNamespace = "http://xmlns.fnis.com.br/Commons/V1")
public class ConsultarAcoesAtendimentoFault extends Exception {
    
    private br.com.fnis.xmlns.commons.v1.FISFaultServiceType fisFaultService;

    public ConsultarAcoesAtendimentoFault() {
        super();
    }
    
    public ConsultarAcoesAtendimentoFault(String message) {
        super(message);
    }
    
    public ConsultarAcoesAtendimentoFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ConsultarAcoesAtendimentoFault(String message, br.com.fnis.xmlns.commons.v1.FISFaultServiceType fisFaultService) {
        super(message);
        this.fisFaultService = fisFaultService;
    }

    public ConsultarAcoesAtendimentoFault(String message, br.com.fnis.xmlns.commons.v1.FISFaultServiceType fisFaultService, Throwable cause) {
        super(message, cause);
        this.fisFaultService = fisFaultService;
    }

    public br.com.fnis.xmlns.commons.v1.FISFaultServiceType getFaultInfo() {
        return this.fisFaultService;
    }
}
