package br.com.fnis.xmlns.services.consultaacoesatendimentoservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-06T16:57:40.221-03:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://xmlns.fnis.com.br/Services/ConsultaAcoesAtendimentoService/V1", name = "ConsultaAcoesAtendimentoService_V1")
@XmlSeeAlso({br.com.fnis.xmlns.commons.v1.ObjectFactory.class, br.com.fnis.xmlns.consultaacoesatendimento.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ConsultaAcoesAtendimentoServiceV1 {

    @WebMethod(action = "http://xmlns.fnis.com.br/Services/ConsultaAcoesAtendimentoService/V1/consultarAcoesAtendimento")
    @WebResult(name = "ConsultarAcoesAtendimentoResponse", targetNamespace = "http://xmlns.fnis.com.br/consultaAcoesAtendimento/V1.xsd", partName = "ConsultarAcoesAtendimentoResponse")
    public br.com.fnis.xmlns.consultaacoesatendimento.v1.ConsultarAcoesAtendimentoResponseType consultarAcoesAtendimento(
        @WebParam(partName = "ConsultarAcoesAtendimentoRequest", name = "ConsultarAcoesAtendimentoRequest", targetNamespace = "http://xmlns.fnis.com.br/consultaAcoesAtendimento/V1.xsd")
        br.com.fnis.xmlns.consultaacoesatendimento.v1.ConsultarAcoesAtendimentoRequestType consultarAcoesAtendimentoRequest
    ) throws ConsultarAcoesAtendimentoFault;
}
