
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.com.fnis.xmlns.services.consultaacoesatendimentoservice.v1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-06T16:57:40.202-03:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "ConsultaAcoesAtendimentoService_V1",
                      portName = "ConsultaAcoesAtendimentoService_V1SOAP",
                      targetNamespace = "http://xmlns.fnis.com.br/Services/ConsultaAcoesAtendimentoService/V1",
                      wsdlLocation = "file:/D:/Projetos/Openshift/spring-boot-cxf-ws/fis_camel_cxfws_app/wsdl/ConsultaAcoesAtendimentoService_V1_1.wsdl",
                      endpointInterface = "br.com.fnis.xmlns.services.consultaacoesatendimentoservice.v1.ConsultaAcoesAtendimentoServiceV1")
                      
public class ConsultaAcoesAtendimentoService_V1SOAPImpl implements ConsultaAcoesAtendimentoServiceV1 {

    private static final Logger LOG = Logger.getLogger(ConsultaAcoesAtendimentoService_V1SOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see br.com.fnis.xmlns.services.consultaacoesatendimentoservice.v1.ConsultaAcoesAtendimentoServiceV1#consultarAcoesAtendimento(br.com.fnis.xmlns.consultaacoesatendimento.v1.ConsultarAcoesAtendimentoRequestType consultarAcoesAtendimentoRequest)*
     */
    public br.com.fnis.xmlns.consultaacoesatendimento.v1.ConsultarAcoesAtendimentoResponseType consultarAcoesAtendimento(br.com.fnis.xmlns.consultaacoesatendimento.v1.ConsultarAcoesAtendimentoRequestType consultarAcoesAtendimentoRequest) throws ConsultarAcoesAtendimentoFault   { 
        LOG.info("Executing operation consultarAcoesAtendimento");
        System.out.println(consultarAcoesAtendimentoRequest);
        try {
            br.com.fnis.xmlns.consultaacoesatendimento.v1.ConsultarAcoesAtendimentoResponseType _return = new br.com.fnis.xmlns.consultaacoesatendimento.v1.ConsultarAcoesAtendimentoResponseType();
            _return.setResponseDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-03-06T16:57:40.218-03:00"));
            _return.setDsAcao("DsAcao1552274640");
            _return.setTpAcao("TpAcao-1860546321");
            _return.setDsTipoAcao("DsTipoAcao-1079965082");
            _return.setStAcao("StAcao811571183");
            _return.setDsStatusAcao("DsStatusAcao-1259163935");
            br.com.fnis.xmlns.consultaacoesatendimento.v1.ListaMotivoType _returnListaMotivo = new br.com.fnis.xmlns.consultaacoesatendimento.v1.ListaMotivoType();
            java.util.List<br.com.fnis.xmlns.consultaacoesatendimento.v1.MotivoType> _returnListaMotivoMotivo = new java.util.ArrayList<br.com.fnis.xmlns.consultaacoesatendimento.v1.MotivoType>();
            br.com.fnis.xmlns.consultaacoesatendimento.v1.MotivoType _returnListaMotivoMotivoVal1 = new br.com.fnis.xmlns.consultaacoesatendimento.v1.MotivoType();
            _returnListaMotivoMotivoVal1.setSeqAcao("SeqAcao-886357777");
            _returnListaMotivoMotivoVal1.setDsSeqAcao("DsSeqAcao-242523199");
            _returnListaMotivoMotivo.add(_returnListaMotivoMotivoVal1);
            _returnListaMotivo.getMotivo().addAll(_returnListaMotivoMotivo);
            _return.setListaMotivo(_returnListaMotivo);
            _return.setUUID("UUID983158187");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ConsultarAcoesAtendimentoFault("consultarAcoesAtendimentoFault...");
    }

}
